services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spacex-frontend
    ports:
      - '3000:3000'
    environment:
      # URL du backend
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:8080/}
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-SpaceX Dashboard}
      NODE_ENV: ${NODE_ENV:-production}
    restart: unless-stopped
    networks:
      - spacex-network

networks:
  spacex-network:
    driver: bridge
